"""
pages/1_Forecast.py

Tourist-facing forecast page: shows historical monthly arrivals + the
12-month Prophet forecast, with COVID and the 2022 economic crisis shaded
as known historical shock periods (not predicted -- see forecast_arrivals.py).

Reads data/processed/arrivals_forecast.csv, which is generated by:
    python src/forecasting/forecast_arrivals.py \
        --arrivals data/processed/sltda_arrivals.csv \
        --output data/processed/arrivals_forecast.csv --periods 12

NOTE: does NOT call st.set_page_config() -- app.py (the router) already
does that once for the whole app. Calling it again here used to crash this
page the moment it was reached through the router (Streamlit only allows
one call per app run).
"""

import os
import sys

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from src.ui.theme import banner_html

FORECAST_CSV = os.path.join("data", "processed", "arrivals_forecast.csv")

# Same shock windows used when training the model (src/forecasting/forecast_arrivals.py)
SHOCK_WINDOWS = [
    ("2019-04-01", "2019-12-31", "Easter Sunday attacks"),
    ("2020-03-18", "2021-12-31", "COVID-19 border closure"),
    ("2022-01-01", "2023-06-30", "Economic crisis"),
]


def inject_styles():
    st.markdown(
        """
        <style>
        div[data-testid="stMetric"] {
            background: #fff; border: 1px solid #e6e2d6; border-radius: 12px;
            padding: 0.8rem 1rem 0.6rem 1rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


@st.cache_data
def load_forecast():
    if not os.path.exists(FORECAST_CSV):
        return None
    df = pd.read_csv(FORECAST_CSV, parse_dates=["date"])
    return df


def build_chart(df):
    fig = go.Figure()

    # Confidence band
    fig.add_trace(go.Scatter(
        x=pd.concat([df["date"], df["date"][::-1]]),
        y=pd.concat([df["forecast_upper"], df["forecast_lower"][::-1]]),
        fill="toself",
        fillcolor="rgba(31, 111, 92, 0.15)",
        line=dict(color="rgba(255,255,255,0)"),
        hoverinfo="skip",
        name="Confidence range",
        showlegend=True,
    ))

    # Forecast line (model fit + future)
    fig.add_trace(go.Scatter(
        x=df["date"], y=df["forecast_arrivals"],
        mode="lines", name="Forecast",
        line=dict(color="#1f6f5c", width=2),
    ))

    # Actual historical points
    actual = df.dropna(subset=["actual_arrivals"])
    fig.add_trace(go.Scatter(
        x=actual["date"], y=actual["actual_arrivals"],
        mode="markers", name="Actual arrivals",
        marker=dict(color="#111111", size=5),
    ))

    # Shaded shock periods
    for start, end, label in SHOCK_WINDOWS:
        fig.add_vrect(
            x0=start, x1=end,
            fillcolor="red", opacity=0.07, line_width=0,
            annotation_text=label, annotation_position="top left",
            annotation=dict(font_size=10, font_color="gray"),
        )

    fig.update_layout(
        xaxis_title="Month",
        yaxis_title="Tourist arrivals",
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        margin=dict(t=60, b=40, l=40, r=20),
        height=520,
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


def main():
    inject_styles()

    st.markdown(
        banner_html(
            "Sri Lanka Tourist Arrivals \u2014 Forecast",
            "Historical monthly arrivals (SLTDA reports, 2019\u20132025) with a "
            "12-month forward forecast. Shaded regions mark known historical "
            "shocks (Easter attacks, COVID border closure, economic crisis) -- "
            "these are flagged as known events in the model, not predicted "
            "into the future.",
            tag="Forecast",
        ),
        unsafe_allow_html=True,
    )

    df = load_forecast()
    if df is None:
        st.error(
            "No forecast data found. Run this first:\n\n"
            "`python src/forecasting/forecast_arrivals.py --arrivals "
            "data/processed/sltda_arrivals.csv --output "
            "data/processed/arrivals_forecast.csv --periods 12`"
        )
        return

    col1, col2, col3 = st.columns(3)
    latest_actual = df.dropna(subset=["actual_arrivals"]).iloc[-1]
    next_forecast = df[df["actual_arrivals"].isna()].iloc[0] if df["actual_arrivals"].isna().any() else None

    col1.metric("Latest recorded month", latest_actual["date"].strftime("%b %Y"),
                f"{int(latest_actual['actual_arrivals']):,} arrivals")
    if next_forecast is not None:
        col2.metric("Next month forecast", next_forecast["date"].strftime("%b %Y"),
                    f"{int(next_forecast['forecast_arrivals']):,} arrivals")
    col3.metric("Forecast horizon", "12 months ahead")

    st.write("")
    st.plotly_chart(build_chart(df), use_container_width=True)

    with st.expander("View underlying data"):
        st.dataframe(
            df[["date", "actual_arrivals", "forecast_arrivals", "forecast_lower", "forecast_upper"]]
            .rename(columns={
                "date": "Month", "actual_arrivals": "Actual",
                "forecast_arrivals": "Forecast", "forecast_lower": "Lower bound",
                "forecast_upper": "Upper bound",
            }),
            use_container_width=True,
        )


if __name__ == "__main__":
    main()
